security:
    providers:
       from_database:
            entity:
                class: App\Entity\User
                property: email
    encoders:
        App\Entity\User:
                algorithm: bcrypt
                cost: 12
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login : 
                check_path: login
            logout:
                path: /logout
                target: /
            guard:
                authenticators:
                    - App\Security\ValidationCodeAuthenticator
                    - App\Security\LoginAuthenticator
                entry_point: App\Security\LoginAuthenticator
    access_control:
        - { path: ^/(login|validation), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        - { path: /admin, roles: ROLE_ADMIN }